server:
  port: 8890

logging:
  path: logs
  file: mylog.log


spring:
  application:
    name: report
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.254.128:3306/course
    username: daqing
    password: qing0221qing

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
